### ISSUE TITLE
review wording

### ISSUE THREAD

**Issue by matthewberryman** [MSFREACH/msf-reach-contacts-scheduler#7]
I will send you an email. Please list any changes here.

**Comment by matthewberryman** [comment]
We do need to hyperlink MSF-REACH to https://msf-reach.org/landing/#about to provide more information about the platform so people know how their information will be used. I will put that in in a commit soon.

**Comment by matthewberryman** [comment]
^^ done, now "REACH platform" is linked, I also fixed "MSF Reach" -> "MSF REACH" in the signature too.

**Comment by LucieGueuning** [comment]
Email to be changed to the following one: 
Hello,

You have been sent this email as your contacts details have been entered into the Médecins Sans Frontières REACH platform by yourself or otherwise, provided to an MSF staff member. To update or delete your contact information, follow the link to the contact form.

Update or remove 
https://test.msf-reach.org/contact/?token=7a218b6f-0a8d-4ebd-8afe-867d401db5ab&email=mberryma@uow.edu.au 

Kind Regards,
MSF REACH Project Team
Privacy policy

**Comment by LucieGueuning** [comment]
with the hyperlink for my email address
with the hyperlink to Privacy Policy

**Comment by matthewberryman** [comment]
@LucieGueuning so link "MSF REACH Project Team" to your email? just double checking

**Comment by matthewberryman** [comment]
About modal done in https://github.com/MSFREACH/msf-reach/issues/450 and deploying now to web site.

**Comment by matthewberryman** [comment]
As a minor grammar point the comma should come after "yourself" so I will adjust that. If happy with that, and email hyperlink text, then close this issue and I will send later tonight.
